name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: CCCshengjiang
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=gradient-blue-purple&color_dots=#bfd6f6
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark&color_snake=gradient-blue-purple&color_dots=#30363d

      - name: Push to output branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
          publish_branch: output
